# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P19_211064018_AMFJ_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 555)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblElementos = QtWidgets.QLabel(self.centralwidget)
        self.lblElementos.setGeometry(QtCore.QRect(20, 20, 49, 16))
        self.lblElementos.setObjectName("lblElementos")
        self.txtElementos = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtElementos.setGeometry(QtCore.QRect(80, 20, 256, 31))
        self.txtElementos.setObjectName("txtElementos")
        self.lblArreglo = QtWidgets.QLabel(self.centralwidget)
        self.lblArreglo.setGeometry(QtCore.QRect(360, 20, 49, 16))
        self.lblArreglo.setObjectName("lblArreglo")
        self.txtArreglo = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtArreglo.setGeometry(QtCore.QRect(410, 20, 256, 31))
        self.txtArreglo.setObjectName("txtArreglo")
        self.lblEjecucion = QtWidgets.QLabel(self.centralwidget)
        self.lblEjecucion.setGeometry(QtCore.QRect(20, 70, 51, 16))
        self.lblEjecucion.setObjectName("lblEjecucion")
        self.txtEjecucion = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtEjecucion.setGeometry(QtCore.QRect(20, 90, 256, 192))
        self.txtEjecucion.setObjectName("txtEjecucion")
        self.btnIniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btnIniciar.setGeometry(QtCore.QRect(360, 120, 75, 24))
        self.btnIniciar.setObjectName("btnIniciar")
        self.btnMostrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnMostrar.setGeometry(QtCore.QRect(360, 150, 75, 24))
        self.btnMostrar.setObjectName("btnMostrar")
        self.btnReiniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btnReiniciar.setGeometry(QtCore.QRect(360, 180, 75, 24))
        self.btnReiniciar.setObjectName("btnReiniciar")
        self.lblContenido = QtWidgets.QLabel(self.centralwidget)
        self.lblContenido.setGeometry(QtCore.QRect(30, 310, 131, 16))
        self.lblContenido.setObjectName("lblContenido")
        self.txtContenido = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtContenido.setGeometry(QtCore.QRect(30, 330, 256, 192))
        self.txtContenido.setObjectName("txtContenido")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblElementos.setText(_translate("MainWindow", "Elementos"))
        self.lblArreglo.setText(_translate("MainWindow", "Arreglo"))
        self.lblEjecucion.setText(_translate("MainWindow", "Ejecucion"))
        self.btnIniciar.setText(_translate("MainWindow", "Iniciar"))
        self.btnMostrar.setText(_translate("MainWindow", "Mostrar"))
        self.btnReiniciar.setText(_translate("MainWindow", "Reiniciar"))
        self.lblContenido.setText(_translate("MainWindow", "Contenido de Arreglos"))