# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\CURSO AGO-DIC 22\Ejemplo Python\TopicosAvanzados\EjemplosGUI\Registros.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrosGUI(object):
    def setupUi(self, RegistrosGUI):
        RegistrosGUI.setObjectName("RegistrosGUI")
        RegistrosGUI.resize(451, 205)
        self.centralwidget = QtWidgets.QWidget(RegistrosGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.label.setMinimumSize(QtCore.QSize(121, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.label_2.setMinimumSize(QtCore.QSize(111, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 20, 141, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 60, 281, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 111, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 100, 281, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.btnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptar.setGeometry(QtCore.QRect(70, 140, 93, 28))
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(250, 140, 93, 28))
        self.btnCancelar.setObjectName("btnCancelar")
        RegistrosGUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RegistrosGUI)
        self.statusbar.setObjectName("statusbar")
        RegistrosGUI.setStatusBar(self.statusbar)

        self.retranslateUi(RegistrosGUI)
        QtCore.QMetaObject.connectSlotsByName(RegistrosGUI)

    def retranslateUi(self, RegistrosGUI):
        _translate = QtCore.QCoreApplication.translate
        RegistrosGUI.setWindowTitle(_translate("RegistrosGUI", "Registros"))
        self.label.setText(_translate("RegistrosGUI", "Número de control"))
        self.label_2.setText(_translate("RegistrosGUI", "Nombre completo"))
        self.label_3.setText(_translate("RegistrosGUI", "Carrera"))
        self.btnAceptar.setText(_translate("RegistrosGUI", "Aceptar"))
        self.btnCancelar.setText(_translate("RegistrosGUI", "Cancelar"))
